name: "Semantic Release"

on:
  push:
    branches:
      - release

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    if: "!contains(github.event.head_commit.message, '[skip release]')"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        # TODO: ensure this is only done after tests have run
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/*"
      - name: Semantic Release
        run: npx semantic-release
        env:
          # This is automatically populated by GitHub:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
